server:
  port: 4000
auth:
  service:
    url: ${AUTH_SERVICE}
logging:
  level:
    web: INFO
    '[com.olisa_td.gatewayservice]': DEBUG
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:4001
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3

        - id: account-service
          uri: http://account-service:4002
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - StripPrefix=3
            - JwtAuth

        - id: transaction-service
          uri: http://transaction-service:4003
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - StripPrefix=3
            - JwtAuth
