server:
  port: 4000
auth:
  service:
    url: ${AUTH_SERVICE}
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:4001
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: account-service-route
          uri: http://account-service:4002
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            - JwtAuth