server:
  port: 4002

auth:
  service:
    url: ${AUTH_SERVICE}


logging:
  level:
    web: INFO
    '[com.olisa_td.accountservice]': DEBUG

spring:
  application:
    name: account-service
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer