server:
  port: 4004

logging:
  level:
    web: INFO
    '[com.olisa_td.emailservice]': DEBUG

spring:
  mail:
   username: ${SPRING_MAIL_USERNAME}
   password: ${SPRING_MAIL_PASSWORD}
   host: smtp.gmail.com
   port: 587
   protocol: smtp
   properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: email-service
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer